ALTER TABLE users ALTER full_name
SET NOT NULL,
    ALTER current_status
SET NOT NULL;
ALTER TABLE employers
ALTER COLUMN company_name
SET NOT NULL,
    ALTER COLUMN company_address
SET NOT NULL,
    ALTER COLUMN is_hiring
SET DEFAULT FALSE;
ALTER TABLE conversations
ALTER COLUMN user_name
SET NOT NULL,
    ALTER COLUMN employer_name
SET NOT NULL,
    ALTER COLUMN date_sent
SET DEFAULT CURRENT_TIMESTAMP;